public class ArthimaticCalculations {
    public void addition(integer a, integer b){
        integer c = a +b;
        system.debug('addition --> ' + c);
    }

    public void subtraction(integer a, integer b){
        integer c = a - b;
    system.debug('subtraction --> ' + c);
    }

    public void multiplication(integer a, integer b, integer d){
        integer c = a * b * d;
        system.debug('multiplication is --> ' + c);
    }
}