public class checkDatatypes {
    public void MethodBoolean(){
        Boolean checkBoolean = true;
        system.debug('The value of the boolean is ' + checkBoolean);
    }

    public void MethodInteger(){
        Integer varfirst = 1;
        Integer varsecond = 2;
        system.debug('First variable is ' + varfirst + ' and second variable is ' + varsecond);
    }

    public void Stringmethod(){
        String varname = 'Name';
        String var2name = 'Seda';
        system.debug(varname + ' ' + var2name);
    }
}