Dog d1 = new Dog();
d1.name = 'Bruno';
d1.color = 'Black';
d1.age = 6;
system.debug('Dog 1 --> ' + d1);


Dog d2 = new Dog();
d2.name = 'Mojo';
d2.color = 'Brown';
d2.age = 2;
system.debug('Dog 2 --> ' + d2);


Dog d3 = new Dog();
d3.name = 'Max';
d3.color = 'Blonde';
d3.age = 1;
system.debug('Dog 3 --> ' + d3);


Dog d4 = new Dog();
d4.name = 'Lucy';
d4.color = 'White';
d4.age = 4;
system.debug('Dog 4 --> ' + d4);

Dog.showDogCount();