lead l1 = new lead();
l1.LastName = 'Trigger Lead 1';
l1.Description = 'Trigger Lead 1 description';
l1.Company = 'softinnovas';

insert l1;

lead l2 = new lead();
l2.LastName = 'Trigger Lead 2';
l2.Description = 'Trigger Lead 2 description';
l2.Company = 'softinnovas';

insert l2;

lead l3 = new lead();
l3.LastName = 'Trigger Lead 3';
l3.Description = 'Trigger Lead 3 description';
l3.Company = 'softinnovas';

insert l3;